const mongoose = require("mongoose");

const productSchema = new mongoose.Schema({
    name:{
        type:String,
        require:true,
        trim:true
    },
    description:{
        type:String,
        require:true,
    },
    price:{
        type:Number,
        require:true,
    },
    discountPrice:{
        type:Number,
    },
    countInStock:{
        type:Number,
        require:true,
        default:0
    },
    sku:{
        type:String,
        unique:true,
        require:true
    },
    category:{
        type:String,
        enum:["ShirtWomen","TrousersWomen","ShirtMen","TrousersMen","Dress"]
    },
    brand:{
        type:String,
        require:true
    },
    sizes:{
        type:[String],
        require:true
    },
    colors:{
        type:[String],
        require:true
    },
    collections:{
        type:String,
        require:true
    },
    material:{
        type:String
    },
    gender:{
        type:String,
        enum:["Men","Women","Unisex"]
    },
    images:[{
        url:{
            type:String,
            require:true
        },
        altText:{
            type:String
        }
    }],
    isFeatured:{
        type:Boolean,
        default:false
    },
    isPublished:{
        type:Boolean,
        default:false
    },
    rating:{
        type:Number,
        default:0
    },
    numReviews:{
        type:Number,
        default:0
    },
    tags:[String],
    user:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"User",
        require:true
    },
    metaTitle:{
        type:String
    },
    metaDescription:{
        type:String
    },
    metaKeywords:{
        type:String
    },
    dimensions:{
        length:Number,
        width:Number,
        height:Number
    },
    weight:Number
},{timestamps:true});
 module.exports = mongoose.model("Product",productSchema);